### ISSUE TITLE
Folders in the Eventing Package do not honor Namespace Provider flag

### ISSUE THREAD

**Issue by stephanjohnson** [IntentArchitect/Support#127]
### What happened?

When creating folders in an `Eventing Package` with the _Namespace Provider_ option set to true, the resulting namespace is not reflecting the folder path, however the folders are physically created in the output.

![image](https://github.com/user-attachments/assets/d05ad5fc-6243-49c8-a1b8-3c2a08c66081)

### Output folder structure
![image](https://github.com/user-attachments/assets/1bb55eb3-8077-4cea-87a8-b551ea6e3ae0)

### Template output
```cs
using Intent.RoslynWeaver.Attributes;
using Verentis.Security.Users.Application.Common.Eventing;
using Verentis.Security.Users.Domain;

[assembly: DefaultIntentManaged(Mode.Fully)]
[assembly: IntentTemplate("Intent.Eventing.Contracts.IntegrationEventMessage", Version = "1.0")]

namespace Verentis.Security.Users.Eventing.Messages;

public record UserActivatedEvent : IEvent
{
    public const string PubsubName = "pubsub";
    public const string TopicName = nameof(UserActivatedEvent);

    public UserActivatedEvent()
    {
        Code = null!;
        Flags = null!;
    }

    public Guid Id { get; init; }
    public string Code { get; init; }
    public UserStatus Status { get; init; }
    public Dictionary<string, string> Flags { get; init; }
    public DateTimeOffset LastTokenRequestedAt { get; init; }
    public bool IsDeleted { get; init; }
    string IEvent.PubsubName => PubsubName;
    string IEvent.TopicName => TopicName;
}
```

### What version of Intent Architect are you using?

4.4.0-beta.1

**Comment by stephanjohnson** [comment]
As a side-note: I am trying to avoid having to include a version (i.e. v1) as a suffix to every event name by making them part of the namespace instead. However this code `public const string TopicName = nameof(UserActivatedEvent);` uses only the class name. 

It would be great if there were an option to use the whole, or partial, fully qualified domain name as the topic for the messages (this is for the `Intent.Dapr.AspNetCore.Pubsub` module).

It is also possible in a large micro-service application that multiple services use the exact same name for integration events, and would be difficult to keep track of every event over multiple projects and packages. This can result in collisions in topic names.

**Comment by JonathanLydall** [comment]
Hi @stephanjohnson,

Thank you for bringing this to our attention, I've logged an issue to make these generated eventing contracts also respect folders they're under which we'll look into as soon as possible.

**Comment by stephanjohnson** [comment]
Hi @JonathanLydall,

I have been thinking about this request a bit, and I feel like I shouldn't be creating a folder structure with v1 as part of that structure. But I also do not want to append V1 to every event.

Is the better approach not taking inspiration from the `Intent.AspNetCore.Versioning` module and allowing us to create a Message/Command version element in the messaging designer, and applying the version using a stereotype to each Message/Command contract?

By doing this the template could take charge of how to apply the metadata, whether it is by appending Vx to each Message/Command, by using a namespace, or (in the case of Dapr) building a custom Topic Name string.

**Comment by JonathanLydall** [comment]
Hi @stephanjohnson,

I feel it's a bit of a "six of one, half a dozen of the other" situation.

Either way one is having to specify that a message is a particular version, but my gut feel is that adding ASP.NET Core Controller like versioning to messaging adds additional complexity to the infrastructure for no real benefit. Whereas versioning in the message name or folder makes it completely transparent this this is a different message which just happens to have a convention in its name/folder.

I think API versioning makes sense since you already have a route concept with parts which are often substituted for other kinds of variables and you are now just doing the same with versioning.

If Intent Architect presently generates infrastructure which can't handle messages of the same name but being in different folders, then we would absolutely consider that a bug and want to fix it.

Either way, we will absolutely make the generated messages respect folders, that they don't was just an unfortunate oversight.

**Comment by jp-seini** [comment]
Hi @stephanjohnson 

We have implemented a fix for this issue. If you update the `Intent.Eventing.Contracts` module to version `5.1.5-pre.1` the issue should be resolved. The namespace on generated Event Messages (as well as Event DTOs) will now take the folder structure into account.

Please don't hesitate to reach out again, or reopen the issue if it hasn’t been resolved to your satisfaction.

Thanks.

**Comment by stephanjohnson** [comment]
Hi @jp-seini,

Thanks for this, but the only change that I see is that the module now correctly implements the folder structure in the `Eventing Package` as part of the c# namespace.

```c#
[assembly: IntentTemplate("Intent.Eventing.Contracts.IntegrationEventMessage", Version = "1.0")]

namespace Endura.Security.Tokens.Eventing.Messages.Token.v1;

public record TokenCreatedEvent : IEvent
{
    public const string PubsubName = "pubsub";
    public const string TopicName = nameof(TokenCreatedEvent);

    public TokenCreatedEvent()
...
```

The only change is:

`namespace Endura.Security.Tokens.Eventing.Messages;`

became

`namespace Endura.Security.Tokens.Eventing.Messages.Token.v1;`

The TopicName is still the same, `nameof(TokenCreatedEvent)`, and this will not use the FQDN for the event name. 

Just as a side note, I do use the `Intent.Dapr.AspNetCore.Pubsub` and not `Intent.Eventing.MassTransit`

**Comment by jp-seini** [comment]
Apologies @stephanjohnson - I did miss that part of the issue. I'll reopen and investigate.

**Comment by stephanjohnson** [comment]
I also see that I mentioned the FQDN requirement in a comment

> It would be great if there were an option to use the whole, or partial, fully qualified domain name as the topic for the messages (this is for the Intent.Dapr.AspNetCore.Pubsub module).

So then technically this issue is closed 😄

**Comment by stephanjohnson** [comment]
Hi @jp-seini,

I saw that the `Intent.Dapr.AspNetCore.Pubsub` module got updated, and it updates the topic name to match the FQDN ❤ 

The resulting code is perfect, will be testing it a bit later today.

Thank you.

**Comment by jp-seini** [comment]
Hi @stephanjohnson - Yes, the update to that module went out late on Friday. Thanks for per-emtavely checking it, and I am glad its now working as expected.

**Comment by jp-seini** [comment]
@stephanjohnson  - just a note on updating `Intent.Dapr.AspNetCore.Pubsub` for existing applications. 

Any `Messages` in an existing application when upgrading to `Intent.Dapr.AspNetCore.Pubsub - 3.0.0-pre.1` will have the old topic name preserved for backwards compatibility. Any new messages created will use the new topic structure.

If you would like the "older" messages to use the new topic structure as well, the `Topic Name` on the `Message` in the _Service Designer_ can be set to blank.

If you have any questions on this please do reach out.
